version: '3.8'

services:
  # 1. THE WEB APP (Your Flask Code)
  web:
    build: .
    container_name: skhokho-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db  # Wait for the database to start first
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
      # The Connection String: user:password@hostname:port/dbname
      - DATABASE_URL=postgresql://skhokho_user:skhokho_pass@db:5432/skhokho_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} 
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    restart: always

  # 2. THE DATABASE (PostgreSQL)
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: skhokho-db
    environment:
      POSTGRES_USER: skhokho_user
      POSTGRES_PASSWORD: skhokho_pass
      POSTGRES_DB: skhokho_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
# Define the volume storage
volumes:
  postgres_data: